version: '3.8'

services:
  castcle-web:
    container_name: castcle-web
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: castcle/castcle-web:latest
    ports:
      - 4200:80
    environment:
      - TZ=Asia/Bangkok

networks:
  castcle-gateway:
    name: castcle-gateway
    external: true
